/* eslint-disable @next/next/no-img-element */
"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Method = { id: string; code: string; name: string; description: string | null; account_name: string | null; account_number: string | null; bank_name: string | null; instructions: string | null; qrUrl: string | null };

export function PaymentProofForm({ paymentId, orderNumber, amount, methods }: { paymentId: string; orderNumber: string; amount: number; methods: Method[] }) {
  const router = useRouter();
  const [methodId, setMethodId] = useState(methods[0]?.id || ""); const [referenceNumber, setReferenceNumber] = useState(""); const [note, setNote] = useState(""); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [toast, setToast] = useState("");
  const method = useMemo(() => methods.find((item) => item.id === methodId), [methodId, methods]);
  async function copy(value: string | null, label: string) { if (!value) return; await navigator.clipboard.writeText(value); setToast(`${label} copied.`); window.setTimeout(() => setToast(""), 1800); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!file || !methodId) return setError("Choose a payment method and upload your receipt."); setBusy(true); try { const receiptResponse = await fetch(`/api/payment-requests/${paymentId}/receipt`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contentType: file.type, sizeBytes: file.size }) }); const receipt = await receiptResponse.json(); if (!receiptResponse.ok) throw new Error(receipt.error || "Unable to prepare receipt upload."); const upload = await fetch(receipt.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!upload.ok) throw new Error("Receipt upload failed. Please try again."); const response = await fetch(`/api/payment-requests/${paymentId}/submit`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paymentMethodId: methodId, referenceNumber, userNote: note }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to submit payment."); router.push(`/payment/submitted?id=${paymentId}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to submit payment."); setBusy(false); } }
  if (!methods.length) return <div className="empty-state"><h3>Payment setup is in progress</h3><p>No payment method is enabled yet. Please contact support or try again later.</p></div>;
  return <form onSubmit={submit}>{toast && <div className="copy-toast">{toast}</div>}<div className="method-grid">{methods.map((item) => <button type="button" className={`method-card ${item.id === methodId ? "selected" : ""}`} key={item.id} onClick={() => setMethodId(item.id)}><b>{item.name}</b><span>{item.description}</span></button>)}</div>{method && <div className="instructions-card"><div><small>PAY USING</small><h2>{method.name}</h2></div><div className="payment-details">{method.account_name && <button type="button" onClick={() => copy(method.account_name, "Account name")}><span>Account name</span><b>{method.account_name}</b><i>Copy</i></button>}{method.account_number && <button type="button" onClick={() => copy(method.account_number, "Account number")}><span>Account number</span><b>{method.account_number}</b><i>Copy</i></button>}{method.bank_name && <div><span>Bank</span><b>{method.bank_name}</b></div>}<button type="button" onClick={() => copy(String(amount), "Amount")}><span>Exact amount</span><b>₱{amount.toLocaleString()}</b><i>Copy</i></button><button type="button" onClick={() => copy(orderNumber, "Order number")}><span>Order</span><b>{orderNumber}</b><i>Copy</i></button></div>{method.qrUrl && <img className="payment-qr" src={method.qrUrl} alt={`${method.name} payment QR code`} />}<p className="instruction-copy">{method.instructions || "Send the exact amount to the account above, save the successful transaction reference, and take a clear screenshot of the receipt."}</p></div>}<div className="field"><label htmlFor="reference">Transaction / reference number</label><input id="reference" required minLength={4} maxLength={100} value={referenceNumber} onChange={(e) => setReferenceNumber(e.target.value)} placeholder="Enter the reference shown on your receipt" /></div><div className="field"><label htmlFor="receipt">Payment receipt</label><input id="receipt" required type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /><small>JPG, PNG, or WEBP. Maximum 5 MB.</small></div><div className="field"><label htmlFor="note">Note (optional)</label><textarea id="note" rows={3} maxLength={500} value={note} onChange={(e) => setNote(e.target.value)} /></div>{error && <div className="form-error">{error}</div>}<button className="btn btn-primary" style={{ width: "100%" }} disabled={busy}>{busy ? "Submitting securely…" : "Submit payment for review"}</button><p className="security-note">Submitting proof does not activate your plan. An administrator must verify and approve the payment.</p></form>;
}
