import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { UpgradeButton } from "@/components/billing/upgrade-button";
import { PLAN_COPY } from "@/lib/plans";
import { effectivePaymentStatus, formatDate, formatPhp, paymentStatusLabel } from "@/lib/billing/format";

export default async function BillingPage(){
  const s=await createClient(); const {data:{user}}=await s.auth.getUser();
  const [{data:plans},{data:sub},{data:payments},{data:methods}]=await Promise.all([s.from("plans").select("*").eq("active",true).order("price_php"),s.from("subscriptions").select("plan_code,status,period_start,period_end").eq("status","ACTIVE").gt("period_end",new Date().toISOString()).order("period_end",{ascending:false}).limit(1).maybeSingle(),s.from("payment_requests").select("id,order_number,plan_code,payment_method_id,amount_php,status,created_at,expires_at,rejection_reason").order("created_at",{ascending:false}).limit(12),s.from("payment_methods").select("id,name")]);
  const methodNames=new Map((methods||[]).map((m)=>[m.id,m.name]));
  return <><div className="page-head"><div><h1>Billing</h1><p>Renewable 30-day access passes paid by manual transfer. No automatic charges.</p></div></div>{sub&&<div className="panel" style={{marginBottom:12}}><div className="panel-head"><h2>Current access</h2><span className="status active">Active</span></div><p style={{color:"var(--muted)",fontSize:".8rem"}}><strong style={{color:"var(--text)"}}>{sub.plan_code}</strong> · {formatDate(sub.period_start)} to {formatDate(sub.period_end)}</p></div>}<div className="billing-grid">{(plans||[]).map(p=><article className={`price-card billing-plan ${sub?.plan_code===p.code?"current":""}`} key={p.code}><h3>{p.name}</h3><div className="price"><b>{formatPhp(p.price_php)}</b><span>{p.code==='FREE'?'no payment':`per ${p.duration_days || 30} days`}</span></div><p style={{color:"var(--muted)",fontSize:".78rem"}}>{PLAN_COPY[p.code as keyof typeof PLAN_COPY]?.tagline}</p><div className="price-divider"/>{PLAN_COPY[p.code as keyof typeof PLAN_COPY]?.features.map(f=><div className="price-feature" key={f}><span>✓</span>{f}</div>)}{p.code==='FREE'?<button className="btn btn-secondary" disabled>Included</button>:<UpgradeButton planCode={p.code as 'CREATOR'|'PRO'} current={sub?.plan_code===p.code}/>}</article>)}</div><div className="panel table-wrap" style={{marginTop:20}}><div className="panel-head"><h2>Payment history</h2></div>{payments?.length?<table className="table"><thead><tr><th>Order</th><th>Plan</th><th>Amount</th><th>Method</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>{payments.map(p=>{const status=effectivePaymentStatus(p.status,p.expires_at);return <tr key={p.id}><td><strong>{p.order_number}</strong></td><td>{p.plan_code}</td><td>{formatPhp(p.amount_php)}</td><td>{p.payment_method_id?methodNames.get(p.payment_method_id)||"—":"—"}</td><td><span className={`status ${status.toLowerCase()}`}>{paymentStatusLabel[status]||status}</span></td><td>{formatDate(p.created_at)}</td><td>{status==='AWAITING_PAYMENT'?<Link href={`/payment/${p.id}`}>Continue</Link>:status==='REJECTED'?<span title={p.rejection_reason||"Rejected"}>Review reason</span>:null}</td></tr>})}</tbody></table>:<div className="empty-state">No payment requests yet.</div>}</div><p className="security-note">Account: {user?.email}. Payments are verified manually before access or credits are granted.</p></>;
}
