// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/payments" | "/admin/payments/[id]" | "/admin/settings/payments" | "/app/billing" | "/app/dashboard" | "/app/help" | "/app/jobs" | "/app/library" | "/app/new" | "/app/projects" | "/app/projects/[id]" | "/app/settings" | "/contact" | "/forgot-password" | "/login" | "/payment/[id]" | "/payment/submitted" | "/privacy" | "/reset-password" | "/signup" | "/terms"
type AppRouteHandlerRoutes = "/api/admin/payment-methods/[id]" | "/api/admin/payment-methods/[id]/qr" | "/api/admin/payments/[id]/approve" | "/api/admin/payments/[id]/reject" | "/api/health" | "/api/payment-requests" | "/api/payment-requests/[id]/receipt" | "/api/payment-requests/[id]/submit" | "/api/projects" | "/api/uploads/complete" | "/api/uploads/presign" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/app"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/payments": {}
  "/admin/payments/[id]": { "id": string; }
  "/admin/settings/payments": {}
  "/api/admin/payment-methods/[id]": { "id": string; }
  "/api/admin/payment-methods/[id]/qr": { "id": string; }
  "/api/admin/payments/[id]/approve": { "id": string; }
  "/api/admin/payments/[id]/reject": { "id": string; }
  "/api/health": {}
  "/api/payment-requests": {}
  "/api/payment-requests/[id]/receipt": { "id": string; }
  "/api/payment-requests/[id]/submit": { "id": string; }
  "/api/projects": {}
  "/api/uploads/complete": {}
  "/api/uploads/presign": {}
  "/app": {}
  "/app/billing": {}
  "/app/dashboard": {}
  "/app/help": {}
  "/app/jobs": {}
  "/app/library": {}
  "/app/new": {}
  "/app/projects": {}
  "/app/projects/[id]": { "id": string; }
  "/app/settings": {}
  "/auth/callback": {}
  "/contact": {}
  "/forgot-password": {}
  "/login": {}
  "/payment/[id]": { "id": string; }
  "/payment/submitted": {}
  "/privacy": {}
  "/reset-password": {}
  "/signup": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/app": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
